### ISSUE TITLE
Feedback link in header broken, goes to white page

### ISSUE THREAD

**Issue by suzialeksander** [berkeleybop/berkeleybop.github.io#15]
The header Feedback icon (with the envelope) on http://www.berkeleybop.org/index.html hangs on a white page, probably not what it was meant to do.

>javascript:(function()%7BSendLinkByMail()%3B%7D)()%3B

**Comment by nlharris** [comment]
You're right. I'm not sure how to fix it. Maybe we should just point the Feedback link to https://github.com/berkeleybop/berkeleybop.github.io/issues/new
Probably better than getting random emails.
