### ISSUE TITLE
New page for Justin Reese

### ISSUE THREAD

**Issue by nlharris** [berkeleybop/berkeleybop.github.io#17]
Add new People page for @justaddcoffee (why does it not seem to recognize his github id?).

**Comment by nathandunn** [comment]
@nlharris  It doesn't recognize it here because @justaddcoffee is not set as a team member yet

**Comment by nlharris** [comment]
https://github.com/berkeleybop/berkeleybop.github.io/tree/master/people/justin-reese
Justin, please edit (and add a picture)!

**Comment by justaddcoffee** [comment]
done, thanks Nomi

**Comment by nlharris** [comment]
you need to edit the index.md in that directory to point to your image (and you can edit other stuff in there while you're at it)

**Comment by justaddcoffee** [comment]
Okies, done, thanks Nomi

**Comment by justaddcoffee** [comment]
Okay, added some stuff per our convo. Thanks Nomi!

**Comment by nlharris** [comment]
Looks good! http://berkeleybop.org/people/justin-reese/
