### ISSUE TITLE
Add metadata for Apollo

### ISSUE THREAD

**Issue by cmungall** [berkeleybop/berkeleybop.github.io#2]
https://github.com/berkeleybop/berkeleybop.github.io/tree/master/software/apollo

**Comment by nathandunn** [comment]
@monicacecilia   The last update is here:

http://berkeleybop.github.io/software/apollo/

You should be edit it directly here:

 https://github.com/berkeleybop/berkeleybop.github.io/blob/master/software/apollo/index.md

I wasn't sure if you had added the original text or not.

**Comment by nathandunn** [comment]
So, please feel free to edit the "indented" text as that is what I added (from the original mostly).

**Comment by nlharris** [comment]
this seems done, right @nathandunn ?

**Comment by nathandunn** [comment]
@nlharris  It will work as-is, but there really isn't a homepage for it.

**Comment by nlharris** [comment]
there really isn't a homepage for apollo, you mean? that's ok, not all the projects have homepages. ok to close this issue?

**Comment by nathandunn** [comment]
sure
