### ISSUE TITLE
Update Phenoscape page

### ISSUE THREAD

**Issue by nlharris** [berkeleybop/berkeleybop.github.io#22]
http://berkeleybop.org/project/phenoscape/
I'm not sure what the status of this project is--are we still involved? If so, I will try to rustle up some info on it.
Tagging @cmungall and @kltm

**Comment by cmungall** [comment]
We were involved in the last phase

**Comment by nlharris** [comment]
Ok... so is "Not currently active" accurate?
Should I add more info to the page?

**Comment by nlharris** [comment]
since this project is not currently active it doesn't seem high priority to add more info to the page. closing.
