### ISSUE TITLE
add Recipe for PyPI + GitHub Actions

### ISSUE THREAD

**Issue by turbomam** [berkeleybop/berkeleybop.github.io#49]
https://packaging.python.org/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/

**Comment by nlharris** [comment]
@turbomam how about a PR with this addition in the appropriate place?

**Comment by turbomam** [comment]
I added a hyperlink in https://github.com/berkeleybop/berkeleybop.github.io/blob/master/best_practice.md

Is that too informal?

**Comment by nlharris** [comment]
that's fine. it's best practice to make changes via a PR but this one was simple enough that it's ok to just do a direct commit. thanks!
