### ISSUE TITLE
http://berkeleybop.org/ontologies 503ing

### ISSUE THREAD

**Issue by tgbugs** [berkeleybop/berkeleybop.github.io#5]
Hi, I can't seem to find the right place to submit this ticket, but http://berkeleybop.org/ontologies seems to be throwing 503 errors.

**Comment by nathandunn** [comment]
Were you looking for this?

http://www.berkeleybop.org/project/gene-ontology/

Yeah, that link shows up on google.   Not sure if its supposed to be there or not.

**Comment by tgbugs** [comment]
The specific issue is that I cannot download http://www.berkeleybop.org/ontologies/ncbitaxon/subsets/taxslim.owl

**Comment by kltm** [comment]
Our apologies for the inconvenience.
This is hopefully now cleared; would you mind retrying?
tagging @cmungall

**Comment by tgbugs** [comment]
Yep, working again. Thanks!

**Comment by cmungall** [comment]
Yes it works, not sure what the cause was.

**Comment by kltm** [comment]
@cmungall Infrastructure. Come see me later.
