### ISSUE TITLE
get 404 on search box within a project

### ISSUE THREAD

**Issue by nathandunn** [berkeleybop/berkeleybop.github.io#6]
http://www.berkeleybop.org/project/gene-ontology/

![screen shot 2016-11-13 at 1 06 24 pm](https://cloud.githubusercontent.com/assets/751274/20248876/08f86196-a9a2-11e6-9692-631bcfda9887.png)

**Comment by nlharris** [comment]
this seems to be working for me -- @nathandunn can you test?

**Comment by nathandunn** [comment]
@nlharris It must have gotten fixed at some point. 👍
