### ISSUE TITLE
automatically resize logos

### ISSUE THREAD

**Issue by nlharris** [berkeleybop/berkeleybop.github.io#68]
Project logos show up full-size, which can be way too big. Should constrain logos to be a max size.
(I thought there was an already issue about this but I don't see it.)

<img width="1135" alt="Screen Shot 2022-10-23 at 12 08 44 PM" src="https://user-images.githubusercontent.com/348704/197411128-07fc709b-7a60-43ae-a3d2-759763ab541e.png">

**Comment by cthoyt** [comment]
To fix this, edit the `style="..."` in https://github.com/berkeleybop/berkeleybop.github.io/blob/f4abfe1511d40d6b90196ea6dd4c6d2dae88749b/_layouts/software.html#L7-L9

**Comment by nlharris** [comment]
I'm not very experienced in css and don't know what to change there.   😕
