### ISSUE TITLE
Add more content to best practices page about Python versions and virtual environments

### ISSUE THREAD

**Issue by pkalita-lbl** [berkeleybop/berkeleybop.github.io#70]
Currently the [best practices page](https://berkeleybop.github.io/best_practice#codingpython) make a brief statements that projects should use Python 3.8+ and use `poetry` to manage virtual environments. It seems to be a semi-regular source of confusion as to _how_ to actually accomplish that. I think we should expand that section or add a new one that describes -- starting from scratch -- how to install and use `pyenv` to manage Python versions and how to install and use `poetry` to manage virtual environments. We shouldn't rewrite the entire documentation of those projects, but rather just outline the basic commands needed to get started with a new or existing project.

**Comment by nlharris** [comment]
Great idea! Sounds like it's important enough to need a fair amount of detail, so rather than embedding it in the best practices page, let's create a separate document and point to it from the BPP. (The document could go in our GH or, if it's simpler to maintain, just be a gdoc.)

**Comment by matentzn** [comment]
Interesting: https://gist.github.com/eyeseast/548fddcfd0df24e589375af6a926ef7e

**Comment by pkalita-lbl** [comment]
That's a nice write up and I definitely agree with what's there (although I can't really speak for `pipenv` as I haven't use it too much).
